commit bash-20110525 snapshot

diff --git a/tests/run-heredoc b/tests/run-heredoc
--- a/tests/run-heredoc
+++ b/tests/run-heredoc
@@ -1,2 +1,6 @@
+echo "warning: UNIX versions number signals and schedule processes differently." >&2
+echo "warning: If output differing only in line numbers is produced, please" >&2
+echo "warning: do not consider this a test failure." >&2
+
 ${THIS_SH} ./heredoc.tests > /tmp/xx 2>&1
 diff /tmp/xx heredoc.right && rm -f /tmp/xx
