more test suite changes to partially highlight warning messages; several fixes to bracket expression parsing with equivalence classes, collating symbols, and character classes together with range expressions

diff --git a/tests/run-builtins b/tests/run-builtins
--- a/tests/run-builtins
+++ b/tests/run-builtins
@@ -1,4 +1,4 @@
-echo "warning: some of these tests may fail if process substitution has not" >&2
+echo "${CSTART}warning${CEND}: some of these tests may fail if process substitution has not" >&2
 echo "${TAB}been compiled into the shell or if the OS does not provide" >&2
 echo "${TAB}/dev/fd." >&2
 
diff --git a/tests/run-cond b/tests/run-cond
--- a/tests/run-cond
+++ b/tests/run-cond
@@ -1,8 +1,8 @@
-echo "warning: all of these tests will fail if the conditional command has not" >&2
+echo "${CSTART}warning${CEND}: all of these tests will fail if the conditional command has not" >&2
 echo "${TAB}been compiled into the shell" >&2
-echo "warning: some of these tests will fail if extended pattern matching has not" >&2
+echo "${CSTART}warning${CEND}: some of these tests will fail if extended pattern matching has not" >&2
 echo "${TAB}been compiled into the shell" >&2
-echo "warning: the text of system error messages may vary between systems and" >&2
+echo "${CSTART}warning${CEND}: the text of system error messages may vary between systems and" >&2
 echo "${TAB}produce diff output." >&2
 
 ${THIS_SH} ./cond.tests > ${BASH_TSTOUT} 2>&1
diff --git a/tests/run-execscript b/tests/run-execscript
--- a/tests/run-execscript
+++ b/tests/run-execscript
@@ -12,12 +12,12 @@
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-echo "warning: the text of a system error message may vary between systems and" >&2
+echo "${CSTART}warning${CEND}: the text of a system error message may vary between systems and" >&2
 echo "${TAB}produce diff output." >&2
 echo "${TAB}if the text of the error messages concerning \`notthere' or" >&2
 echo "${TAB}\`/tmp/bash-notthere' not being found or \`/' being a directory" >&2
 echo "${TAB}produce diff output, please do not consider this a test failure" >&2
-echo "warning: if diff output differing only in the location of the bash" >&2
+echo "${CSTART}warning${CEND}: if diff output differing only in the location of the bash" >&2
 echo "${TAB}binary appears, please do not consider this a test failure" >&2
 ${THIS_SH} ./execscript > ${BASH_TSTOUT} 2>&1
 diff ${BASH_TSTOUT} exec.right && rm -f ${BASH_TSTOUT}
diff --git a/tests/run-jobs b/tests/run-jobs
--- a/tests/run-jobs
+++ b/tests/run-jobs
@@ -1,6 +1,6 @@
-echo "warning: some of these tests may fail if job control has not been compiled" >&2
+echo "${CSTART}warning${CEND}: some of these tests may fail if job control has not been compiled" >&2
 echo "${TAB}into the shell" >&2
-echo "warning: there may be a message regarding a cat process dying due to a" >&2
+echo "${CSTART}warning${CEND}: there may be a message regarding a cat process dying due to a" >&2
 echo "${TAB}SIGHUP. Please disregard." >&2
 
 ${THIS_SH} ./jobs.tests > ${BASH_TSTOUT} 2>&1
diff --git a/tests/run-new-exp b/tests/run-new-exp
--- a/tests/run-new-exp
+++ b/tests/run-new-exp
@@ -1,8 +1,8 @@
-echo "warning: two of these tests will fail if your OS does not support" >&2
+echo "${CSTART}warning${CEND}: two of these tests will fail if your OS does not support" >&2
 echo "${TAB}named pipes or the /dev/fd filesystem.  If the tests of the" >&2
 echo "${TAB}process substitution mechanism fail, please do not consider" >&2
 echo "${TAB}this a test failure" >&2
-echo "warning: if you have exported variables beginning with the string _Q," >&2
+echo "${CSTART}warning${CEND}: if you have exported variables beginning with the string _Q," >&2
 echo "${TAB}the tests may generate diff output. If so, please do not consider" >&2
 echo "${TAB}this a test failure" >&2
 
diff --git a/tests/run-nquote4 b/tests/run-nquote4
--- a/tests/run-nquote4
+++ b/tests/run-nquote4
@@ -1,7 +1,7 @@
 # See whether or not we can use `diff -a'
 ( diff -a ./nquote4.right ./nquote4.right >/dev/null 2>&1 ) && AFLAG=-a
 
-echo "warning: some of these tests will fail if you do not have UTF-8" >&2
+echo "${CSTART}warning${CEND}: some of these tests will fail if you do not have UTF-8" >&2
 echo "${TAB}locales installed on your system" >&2
 
 ${THIS_SH} ./nquote4.tests > ${BASH_TSTOUT} 2>&1
diff --git a/tests/run-procsub b/tests/run-procsub
--- a/tests/run-procsub
+++ b/tests/run-procsub
@@ -1,4 +1,4 @@
-echo "warning: all of these tests will fail if process substitution has not" >&2
+echo "${CSTART}warning${CEND}: all of these tests will fail if process substitution has not" >&2
 echo "${TAB}been compiled into the shell or if the OS does not provide" >&2
 echo "${TAB}FIFOs or /dev/fd. Some tests may fail if the OS does not" >&2
 echo "${TAB}provide FIFOs." >&2
diff --git a/tests/run-redir b/tests/run-redir
--- a/tests/run-redir
+++ b/tests/run-redir
@@ -1,6 +1,6 @@
-echo "warning: the text of a system error message may vary between systems and" >&2
+echo "${CSTART}warning${CEND}: the text of a system error message may vary between systems and" >&2
 echo "${TAB}produce diff output." >&2
-echo "warning: if the text of an error message concerning \`redir1.*' not being" >&2
+echo "${CSTART}warning${CEND}: if the text of an error message concerning \`redir1.*' not being" >&2
 echo "${TAB}found or messages concerning bad file descriptors produce diff" >&2
 echo "${TAB}output, please do not consider it a test failure" >&2
 ${THIS_SH} ./redir.tests > ${BASH_TSTOUT} 2>&1
diff --git a/tests/run-varenv b/tests/run-varenv
--- a/tests/run-varenv
+++ b/tests/run-varenv
@@ -1,4 +1,4 @@
-echo "warning: some of these tests will fail if arrays have not" >&2
+echo "${CSTART}warning${CEND}: some of these tests will fail if arrays have not" >&2
 echo "${TAB}been compiled into the shell" >&2
 ${THIS_SH} ./varenv.tests 2>&1 | grep -v '^expect' > ${BASH_TSTOUT}
 diff ${BASH_TSTOUT} varenv.right && rm -f ${BASH_TSTOUT}
diff --git a/tests/run-vredir b/tests/run-vredir
--- a/tests/run-vredir
+++ b/tests/run-vredir
@@ -1,4 +1,4 @@
-echo "warning: the text of a system error message may vary between systems and" >&2
+echo "${CSTART}warning${CEND}: the text of a system error message may vary between systems and" >&2
 echo "${TAB}produce diff output." >&2
 ${THIS_SH} ./vredir.tests > ${BASH_TSTOUT} 2>&1
 diff ${BASH_TSTOUT} vredir.right && rm -f ${BASH_TSTOUT}
