Imported from ../bash-2.02.tar.gz.

diff --git a/tests/run-new-exp b/tests/run-new-exp
--- a/tests/run-new-exp
+++ b/tests/run-new-exp
@@ -1,2 +1,7 @@
+echo "warning: two of these tests will fail if your OS does not support" >&2
+echo "warning: named pipes or the /dev/fd filesystem.  If the tests of the" >&2
+echo "warning: process substitution mechanism fail, please do not consider" >&2
+echo "warning: this a test failure" >&2
+
 ${THIS_SH} ./new-exp.tests 2>&1 | grep -v '^expect' > /tmp/xx
 diff /tmp/xx new-exp.right && rm -f /tmp/xx
