commit bash-20070208 snapshot

diff --git a/tests/run-builtins b/tests/run-builtins
--- a/tests/run-builtins
+++ b/tests/run-builtins
@@ -1,2 +1,5 @@
+echo "warning: some of these tests may fail if process substitution has not" >&2
+echo "warning: been compiled into the shell" >&2
+
 ${THIS_SH} ./builtins.tests > /tmp/xx 2>&1
 diff /tmp/xx builtins.right && rm -f /tmp/xx
